Develop/subgroup3_dev/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("users.urls", namespace="users")),
    path('', include("movies.urls", namespace = "movies"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

Develop/subgroup3_dev/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views as movie_view
from django.conf.urls.static import static
app_name = "movies"

urlpatterns = [
    path('', movie_view.HomeView.as_view(), name="home"),
    path('predict/', movie_view.PredictView.as_view(), name="predict")
]

Develop/subgroup3_dev/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views as user_view

app_name = "users"

urlpatterns = [
    path('hi/', user_view.HomeView.as_view(), name="home")
]

Develop/subgroup3_dev/movies/models.py
from django.db import models

# Create your models here.

class Actor(models.Model):
    name = models.CharField(max_length=20, blank=False)
    weight = models.CharField(max_length=10, blank=False)


class Director(models.Model):
    name = models.CharField(max_length=20, blank=False)
    weight = models.CharField(max_length=10, blank=False)

class Genre(models.Model):
    name = models.CharField(max_length=20, blank=False)
    weight = models.CharField(max_length=10, blank=False)

Develop/subgroup3_dev/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

Develop/subgroup3_dev/movies/forms.py
from django import forms  



class MoviePredictForm(forms.Form):
    # 감독, 배우들 , 예산, 장르 , 제작사
    # 배우 최대 3명까지

    director = forms.CharField(label="감독")
        
    actor1 = forms.CharField(label='배우1')
    actor2 = forms.CharField(label='배우2', required=False)
    actor3 = forms.CharField(label='배우3', required=False)
    genre = forms.CharField(label="장르")
    budget = forms.IntegerField(label="예산")


    


    

Develop/subgroup3_dev/movies/views.py
from django.shortcuts import render,redirect, reverse
from django.views.generic import ListView, FormView
from . import forms
from . import models


class HomeView(ListView):
    def get(self, request):
        return render(request, "home.html", {})


class PredictView(FormView):

    def get(self, request):
        form = forms.MoviePredictForm
        return render(request, "predict.html", {"forms": form})

    def post(self, request):

        director = request.POST.get("director")
        actor1 = request.POST.get("actor1")
        actor2 = request.POST.get("actor2")
        actor3 = request.POST.get("actor3")
        
        genre = request.POST.get("genre")
        budget = request.POST.get("budget")

        decision_value = self.predict(director, actor1, actor2, actor3, genre, budget)


        form = forms.MoviePredictForm
        return render(request, "predict_result.html", {"decision_value": decision_value})


    def predict(self, director, actor1, actor2, actor3, genre, budget):

        def weight_func(DB):
            if DB == 'super-hit':
                return 4
            elif DB == 'hit':
                return 3
            elif DB == 'soso':
                return 2
            else:
                return 1

        def budget_func(budget):
            if int(budget) < 0.95:
                return 1
            elif 0.95 <= int(budget) <= 15:
                return 2
            elif 15 < int(budget) <= 40:
                return 3
            else:
                return 4

        def predict_decision(total):
            if total >= 18:
                return 4
            elif 13 <= total < 18:
                return 3
            elif 8 < total < 13:
                return 2
            else:
                return 1

        try:
            genreDB = models.Genre.objects.get(name=genre)
        except models.Genre.DoesNotExist:
            genreDB = None

        try:
            DirectorDB = models.Director.objects.get(name=director)
        except models.Director.DoesNotExist:
            DirectorDB = None
        
        try:
            Actor1DB = models.Actor.objects.get(name=actor1)
        except models.Actor.DoesNotExist:
            Actor1DB = None
        
        try:
            Actor2DB = models.Actor.objects.get(name=actor2)
        except models.Actor.DoesNotExist:
            Actor2DB = None
        
        try:
            Actor3DB = models.Actor.objects.get(name=actor3)
        except models.Actor.DoesNotExist:
            Actor3DB = None
        
        total_weight = 0
        
        if genreDB is not None:
            total_weight += weight_func(genreDB.weight)

        if DirectorDB is not None:
            total_weight += weight_func(DirectorDB.weight)

        if Actor1DB is not None:
            total_weight += weight_func(Actor1DB.weight)


        if Actor2DB is not None:
            total_weight += weight_func(Actor2DB.weight)
        else:
            if Actor1DB is not None:
                total_weight += weight_func(Actor1DB.weight)


        if Actor3DB is not None:
            total_weight += weight_func(Actor3DB.weight)
        else:
            if Actor1DB is not None:
                total_weight += weight_func(Actor1DB.weight)


            
        total_weight += budget_func(budget)
        
        decision_value = predict_decision(total_weight)
        print(total_weight)
        print(decision_value)

        return decision_value

       

Develop/subgroup3_dev/users/views.py
from django.shortcuts import render
from django.views.generic import ListView
from . import models
# Create your views here.


class HomeView(ListView):
    model = models.User
    template_name = "home.html"
    context_object_name = "users"

Develop/subgroup3_dev/templates/home.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <title>Moving</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{% url "movies:home" %}">
            Moving
        </a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">ㅇㅇ</span>
            
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item ">
        
                </li>
            </ul>
        </div>
    </nav> 
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    <div class="text-center mt-5 mb-5">
        <p>
            <a class="text-center" href="">영화 평가</a>
        </p>

        <p>
            <a class="" href="">영화 추천</a>
        </p>
        <p>
            <a class="" href="{% url "movies:predict" %}">영화 예측</a>
        </p>
    </div>
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

</html>

Develop/subgroup3_dev/templates/predict.html
{% extends 'home.html' %}

{% block content %}

    <h4 class="text-center mt-5">
        영화 흥행 여부를 예측해드려요.
    </h4>

    <form action="{% url "movies:predict" %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for form in forms %}

            <div class="text-center mt-5">
                {{form.label}}: {{form}}
            </div>
        {% endfor %}
        <div class="text-center mb-5 mt-5">
            <input type="submit" class="btn border border-black" value="제출">
        </div>
    </form>

{% endblock %}
    

Develop/subgroup3_dev/templates/predict_result.html
{% extends 'home.html' %}
{% load static %}
{% block content %}

    <h4 class="text-center mt-5">
        영화 예측 결과를 보여드려요.
    </h4>

    {% if decision_value == 4 %}
    <div class="text-center mt-5">
        <img src="{% static 'img/superhit.jpg' %}"></img>
        <h4 class="text-center mt-3 mb-5">super hit</h4>
    </div>
    {% elif decision_value == 3 %}
    <div class="text-center mt-5">
        <img src="{% static 'img/hit.jpg' %}"></img>
        <h4 class="text-center mt-3 mb-5">hit</h4>
    </div>
    {% elif decision_value == 2 %}
    <div class="text-center mt-5">
        <img src="{% static 'img/soso.jpg' %}"></img>
        <h4 class="text-center mt-3 mb-5">soso</h4>
    </div>     
    {% elif decision_value == 1 %}
    <div class="text-center mt-5">
        <img src="{% static 'img/poor.jpg' %}"></img>
        <h4 class="text-center mt-3 mb-5">poor</h4>
    </div>
    {% endif %}

{% endblock %}