Develop/subgroup2_dev/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include("users.urls", namespace="users")),
    path('', include("movies.urls", namespace="movies"))
]

Develop/subgroup2_dev/movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views as movie_view

app_name = "movies"

urlpatterns = [
    path('eval', movie_view.MovieEvalView.as_view(), name="evaluate"),
    path('', movie_view.HomeView.as_view(), name="home"),
    path('recommend', movie_view.MovieRecView.as_view(), name='recommend')
]

Develop/subgroup2_dev/users/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from . import views as user_view

app_name = "users"

urlpatterns = [

]

Develop/subgroup2_dev/evaluates/models.py
from django.db import models

# Create your models here.
class Evaluate(models.Model):
    user = models.CharField(max_length=10, default="유호성")
    keyword = models.CharField(max_length=100, default="")

Develop/subgroup2_dev/movies/models.py
from django.db import models

# Create your models here.
class MovieModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=40)
    director = models.CharField(max_length=10)
    keyword = models.CharField(max_length=10, blank=True)

Develop/subgroup2_dev/recommends/models.py
from django.db import models

from movies import models as movie_model
# Create your models here.
class Recommend(models.Model):
    user = models.CharField(max_length=10, default="youhoseong")
    keyword = models.CharField(max_length=100, default="")
    movie = models.ManyToManyField(movie_model.MovieModel, related_name="recommend")

    

Develop/subgroup2_dev/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

Develop/subgroup2_dev/movies/forms.py
from django import forms 
#from django.contrib.postgres.fields import ArrayField

class MovieEvalForm(forms.Form):
    score = forms.IntegerField(max_value = 5, min_value=1, label="별점")

Develop/subgroup2_dev/evaluates/views.py
from django.shortcuts import render

# Create your views here.

Develop/subgroup2_dev/movies/views.py
from django.shortcuts import render
from django.views.generic import FormView, ListView
from . import forms
from . import models
import random
from django.shortcuts import render, redirect, reverse
from evaluates import models as eval_model

# Create your views here.

class HomeView(ListView):
    def get(self, request):
        return render(request, "home.html", {})  
    

class MovieRecView(ListView):
    def get(self, request):
        movie_model = models.MovieModel.objects.all()
        try:
            Eval_model = eval_model.Evaluate.objects.get(user="유호성")
            print(Eval_model.keyword == '')

            eval_keyword_list = []
            if Eval_model.keyword != '':
                eval_keyword_list = Eval_model.keyword.split(' ')

            recommend_list = []

            for rkeyword in eval_keyword_list:
                recommend_list += list(models.MovieModel.objects.filter(keyword__contains = rkeyword))

            return render(request, "movie/movie_rec.html", {"eval": Eval_model, "recommend": recommend_list})
        except:
            random_items = random.sample(list(movie_model),10)
            return render(request, "movie/movie_rec.html", {})

        


class MovieEvalView(FormView):
    template_name = "movie/movie_eval.html"

    #recommended_movie = []

    def evaluator(self, keyword_list, user):
        duplicate_keyword_delete_list = list(set(keyword_list))
        recommended_keyword_list = []

        for keyword in duplicate_keyword_delete_list:
            if keyword_list.count(keyword) >= 3:
                recommended_keyword_list.append(keyword)
        keywordStr = ' '.join(recommended_keyword_list)
  
        recommended_movie_list = []
        for rkeyword in recommended_keyword_list:
            recommended_movie_list += list(models.MovieModel.objects.filter(keyword__contains = rkeyword))


        for i in recommended_movie_list:
            print(i)


        print(type(recommended_movie_list))

        Eval_model, created = eval_model.Evaluate.objects.update_or_create(user=user, defaults={
            "user":user, "keyword": keywordStr
        })
        Eval_model.save()
        

        
    def post(self, request):
        movie_id_list = request.POST.getlist("id")
        score_list = request.POST.getlist("score")
        keyword_list = []
        for i in range(len(score_list)):
            if int(score_list[i]) > 3:
                movie_obj = models.MovieModel.objects.get(id=movie_id_list[i])
                keyword = movie_obj.keyword
               
                for key in keyword.split():
                    keyword_list.append(key)

        print(keyword_list)

        if len(keyword_list) >= 5:
            self.evaluator(keyword_list, "유호성")
        return redirect(reverse("movies:evaluate"))

    def get(self, request):
        form_class = forms.MovieEvalForm
        movie_model = models.MovieModel.objects.all()

        try:
            Eval_model = eval_model.Evaluate.objects.get(user="유호성")
            print(Eval_model.keyword == '')

            eval_keyword_list = []
            if Eval_model.keyword != '':
                eval_keyword_list = Eval_model.keyword.split(' ')

            random_items = random.sample(list(movie_model),10)
            return render(request, "movie/movie_eval.html", {"movies": random_items, "form": form_class, "eval": Eval_model})
        except:
            random_items = random.sample(list(movie_model),10)
            return render(request, "movie/movie_eval.html", {"movies": random_items, "form": form_class})

Develop/subgroup2_dev/recommends/views.py
from django.shortcuts import render

# Create your views here.

Develop/subgroup2_dev/users/views.py
from django.shortcuts import render
from django.views.generic import ListView
from . import models
# Create your views here.

Develop/subgroup2_dev/templates/home.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <title>Moving</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
        <a class="navbar-brand" href="{% url "movies:home" %}">
            Moving
        </a>
        <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">ㅇㅇ</span>
            
        </button>
        <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item ">
        
                </li>
            </ul>
        </div>
    </nav>
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    <div class="text-center mt-5 mb-5">
        <p>
            <a class="text-center" href="{% url "movies:evaluate" %}">영화 평가</a>
        </p>

        <p>
            <a class="" href="{% url "movies:recommend" %}">영화 추천</a>
        </p>
        <p>
            <a class="" href="">영화 예측</a>
        </p>
    </div>
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

</html>

Develop/subgroup2_dev/templates/movie/movie_eval.html
{% extends "home.html" %}

{% block content %}
<h4 class="text-center mb-5 mt-5">
10가지 영화를 평가해주세요.
</h4>



<form action="{% url "movies:evaluate" %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for movie in movies %}
        <div class="text-center">
            <div class="mb-3">

                {{movie.title}}

                <input type="hidden" value={{movie.id}} name="id"/>
                <div>
                    {{form}}
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="text-center mb-5">
        <input type="submit" class="btn border border-black" value="다 했어요.">
    </div>
</form>

<p class="text-center">
    {% if eval is not None %}
        <a href="{% url "movies:recommend" %}">
        추천 영화를 보여드릴까요?
        </a>
    {% endif %}
</p>


{% endblock %}

Develop/subgroup2_dev/templates/movie/movie_rec.html
{% extends "home.html" %}
{% block content %}

<h4 class="text-center mt-5 mb-5">
 추천 영화를 보여드려요.
</h4>

<p class="text-center text-muted">
{% if eval is None %}
    영화를 먼저 평가해주세요.

    <a href="{% url "movies:evaluate" %}"> 평가 하러가기 </a>
{% else %}
    {{eval.user}}님은 [{{eval.keyword}}]를 좋아하시네요.

    <div>
    {% for rec in recommend %}
    <div class ="text-center mb-2 text-dark">
        {{rec.title}}
    </div>
    {% endfor %}

    </div>
{% endif %}
</p>




{% endblock %}